[package]
name = "disk_analyzer"
version = "0.1.0"
authors = ["Blair Urish <burace17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humansize = "1.1.0"
relm = "^0.20.0"
relm-derive = "^0.20.0"
mime_guess = "2.0.3"
thiserror = "1.0"
glib = "^0.10.0"

[dependencies.gtk]
version = "^0.9.0"
features = ["v3_16"]

[dependencies.gdk-pixbuf]
version = "^0.9.0"

[dependencies.gio]
version = ""
features = ["v2_44"]