[package]
name = "disk_analyzer"
version = "2024.1.0"
authors = ["Blair Urish <burace17@gmail.com> + AJ Snow :3"]
edition = "2021"

[[bin]]
name = "entry"
path = "src/entry.rs"

[package.metadata.'rust']
main = "src/entry.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
iced = "*"
frunk = "*"
railsgun = "*"
humansize = "*"
mime_guess = "*"
thiserror = "*"
rpds = "*"