[package]
name = "disk_analyzer"
version = "0.1.0"
authors = ["Blair Urish <burace17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#glib = "0.10.3"
humansize = "1.1.0"
relm = "^0.19.0"
relm-derive = "^0.19.0"

[dependencies.gtk]
version = "^0.8.0"
features = ["v3_16"]

[dependencies.gio]
version = ""
features = ["v2_44"]
